export interface ApiResponse {
  success: boolean;
  data: Property[];
  message: string;
  count: number;
  nbPages: number | null;
}

export interface Property {
  id: number;
  typ: number;
  cla: null;
  tra: string;
  lie: number;
  id_parent: null;
  cnt: string | null;
  cli: number | null;
  vli: null;
  prix: number;
  tel: string;
  texte: string;
  date_deb_aff: string;
  nb_chambre: number;
  has_jardin: boolean | null;
  nb_photos: number;
  reference: string;
  nb_pieces: number;
  exposition: string | null;
  cuisine: string | null;
  nb_salles_de_bain: number | null;
  has_grenier: boolean;
  has_terrasse: boolean;
  proximite_transports: string | null;
  proximite_ecoles: string | null;
  proximite_commerces: string | null;
  type_chauffage: string | null;
  nb_etages: number | null;
  has_ascenseur: boolean;
  nb_stationnements: number | null;
  type_stationnement: string | null;
  surface_terrain: number;
  nb_chambres_rdc: number | null;
  nb_salles_d_eau: number | null;
  has_cave: boolean;
  has_veranda: boolean;
  etage: string | null;
  has_interphone: boolean;
  has_balcon: boolean;
  chauffage: string | null;
  surface: number;
  frais_agence: number | null;
  charges: number | null;
  disponibilite: string | null;
  video: null;
  pro: string | null;
  date_creation: string;
  dpe_chiffre: number | null;
  dpe_lettre: string | null;
  ges_chiffre: number | null;
  ges_lettre: string | null;
  exclu: boolean | null;
  nb_lots_copro: null;
  charges_copro: number | null;
  redressement_syndic: boolean | null;
  frais_pourcent: number | null;
  adresse_geoloc: string;
  lat: number | null;
  lng: number | null;
  date_prix_negocie: string | null;
  url_visite_virtuelle: null;
  is_pnf: boolean;
  typ_lib: string;
  typ_encode: string;
  cla_lib: null;
  cla_encode: null;
  lieu_id: number;
  lieu_lib: string;
  lieu_encode: string;
  baisse_prix_montant: number | null;
  baisse_prix_pourcent: number | null;
  has_parquet: boolean;
  has_placard: boolean;
  has_dressing: boolean;
  honoraires_etat_des_lieux: null;
  charges_vendeur: boolean | null;
  previsite_video: boolean;
  previsite_visite_virtuelle: boolean;
  departement_id: number;
  region_id: number;
  is_littoral: null;
  garantie: number;
  regul_charges: number;
  vue_mer: boolean;
  piscine: boolean;
  vendu: null;
  internet: null;
  dpe_date: string | null;
  conso_min: number | null;
  conso_max: number | null;
  plain_pied: boolean;
  loyer_encadre: boolean | null;
  loyer_hc: null;
  loyer_reference: null;
  loyer_complement: null;
  viager: boolean;
  rente: null;
  colocation: boolean | null;
  meuble: boolean | null;
  georisques: boolean;
  url_externe: null;
  annonce_tags: string | null;
  display_georisques: boolean;
  transac_lib: string;
  transac_lib_encode: string;
  quartier: Quartier | null;
  lieu: Lieu;
  photo_url: string;
  photos: string[];
  tel2: string;
  cli_id_tan: string;
  client: Client;
  global_dpe_lettre: string | null;
  has_email: boolean;
  has_video: boolean;
  has_visite_virtuelle: boolean;
  is_geoloc: boolean;
}

export interface Quartier {
  id: number;
  parentId: number;
  code: null;
  type: string;
  libelle: string;
  insee: string;
  cp: string;
  encode: string;
  lat: number;
  lng: number;
  nb_annonces: number;
  zoneId: string;
  littoral: null;
  population: null;
  lieudit: number;
  delegue: number;
  ancienne: number;
  slug_transac: string;
  slug_kl: string;
  libelle_prep: string;
  parent: Lieu;
  features: Features;
}

export interface Lieu {
  id: number;
  parentId: number;
  code: string | null;
  type: string;
  libelle: string;
  insee: string | null;
  cp: string | null;
  encode: string;
  lat: number;
  lng: number;
  nb_annonces: number;
  zoneId: string | null;
  littoral: number | null;
  population: number | null;
  lieudit: number;
  delegue: number;
  ancienne: number;
  slug_transac: string;
  slug_kl: string;
  libelle_prep: string;
  parent: Lieu | null;
  hasChildren: boolean;
  features: Features;
  hasQuartier?: boolean;
}

export interface Features {
  lieuCreditAgricole: string;
}

export interface Client {
  id: number;
  lie: number;
  id_tan: string;
  matricule: string;
  sous_compte: string;
  siret: string;
  enseigne: string;
  raison_sociale: string;
  adresse: string;
  code_postal: string;
  lat: number;
  lng: number;
  date_maj: string;
  phonetracker: boolean | null;
  vitrine_nom: string;
  vitrine_telephone: string;
  vitrine_telephone_loc: string;
  vitrine_email: string;
  vitrine_email_loc: string | null;
  vitrine_logo: string;
  vitrine_photo: string | null;
  vitrine_accroche: string;
  vitrine_accroche2: string | null;
  vitrine_descriptif: string;
  vitrine_site: string;
  vitrine_site2: string | null;
  V3D_colors: null;
  V3D_actif: boolean;
  V3D_directeur_photo: null;
  V3D_photo_ofi: null;
  geoloc_actif: boolean;
  num_adresse_actif: boolean;
  autodiffusion: boolean;
  relance_bap: boolean;
  relance_email: null;
  encode: string;
  hasPackVisibilite: boolean;
  vitrine_adresse: string;
  vitrine_idlie: number;
  fb_page: null;
  opi_id: number | null;
  opi_rating: number | null;
  opi_survey: number | null;
  url_bareme: string | null;
  affichage_adresse_vente: number;
  superuser: number;
  tag: string;
  nb_vente: number;
  nb_loc: number;
  nb_vendu: number;
  nb_exclu: number;
  nb_pnf: number;
  has_annonces: boolean;
  contrat_actif: number;
  business_actif: number;
  opi_origin: string | null;
  nb_vente_maison: number;
  nb_vente_appartement: number;
  nb_loc_maison: number;
  nb_loc_appartement: number;
  vitrine_horaires: string | null;
  bpr_id: string | null;
  agenda_id: null;
  telephone: string | null;
  telephone2: null;
  fax: null;
  urlLogo: string;
  urlPhoto: string;
  urlDirecteurPhoto: string;
  hasPackEclu: boolean;
  libelle: string;
  appellation: string | null;
  vitrine: Vitrine;
  siren: string;
  url_tarifs: string;
  has_avis: boolean;
  avis: Avis;
  hasV3d: boolean;
  v3d: V3d;
  lieu: Lieu;
}

export interface Vitrine {
  adresse: string;
  cp: string;
  ville: string;
}

export interface Avis {
  note: number | null;
  total: number | null;
}

export interface V3d {
  url_vitrine: null;
  url_liste: null;
}
